import Head from "next/head";
import { Vazirmatn } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { getAllCourses, Course } from "@/src/api/course.api";
import { User, getUserData } from "@/src/api/auth.api";
import Link from "next/link";

const vazir = Vazirmatn({ subsets: ["latin"] });

type HomePageProps = {
  courses: Course[];
  user: User;
};
export default function Home({ courses, user }: HomePageProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {user ? <p>{`سلام ${user.first_name} ${user.last_name}`}</p> : null}
      </div>
      <main className={`${styles.main} ${vazir.className}`}>
        <ul>
          {courses.map((course) => (
            <li key={course.id}>
              <div>
                <h3>{course.title}</h3>
                <p>{course.description}</p>
                <p>{course.information}</p>
                {course.isOpen ? (
                  <Link href={`/courses/${course.id}`}>
                    <button>ثبت نام</button>
                  </Link>
                ) : (
                  <p>ثبت نام تکمیل شده است</p>
                )}
              </div>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
}

// server side rendering (SSR)
export async function getServerSideProps() {
  const courses = await getAllCourses();
  const user = await getUserData();
  return {
    props: {
      courses,
      user,
    },
  };
}
